# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and deploy to GH Pages
on: push
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: startsWith(github.ref, 'refs/tags/')
      - name: Use Node.js ${{ matrix.node-version }}
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn
        if: startsWith(github.ref, 'refs/tags/')
      - run: yarn build
        if: startsWith(github.ref, 'refs/tags/')

      - name: Release
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
